$(function(){
    $(".sub_menu").hide();
    $(".main01").mouseover(function(){
        $(".sub01").show();
        $(".sub02").hide();
        $(".sub03").hide();
        $(".sub04").hide();
        $(".sub05").hide();
        $(".sub06").hide();
    });
    $(".main02").mouseover(function(){
        $(".sub01").hide();
        $(".sub02").show();
        $(".sub03").hide();
        $(".sub04").hide();
        $(".sub05").hide();
        $(".sub06").hide();
    });
    $(".main03").mouseover(function(){
        $(".sub01").hide();
        $(".sub03").show();
        $(".sub02").hide();
        $(".sub04").hide();
        $(".sub05").hide();
        $(".sub06").hide();
    });
    $(".main04").mouseover(function(){
        $(".sub01").hide();
        $(".sub04").show();
        $(".sub02").hide();
        $(".sub03").hide();
        $(".sub05").hide();
        $(".sub06").hide();
    });
    $(".main05").mouseover(function(){
        $(".sub01").hide();
        $(".sub05").show();
        $(".sub02").hide();
        $(".sub03").hide();
        $(".sub04").hide();
        $(".sub06").hide();
    });
    $(".main06").mouseover(function(){
        $(".sub01").hide();
        $(".sub06").show();
        $(".sub02").hide();
        $(".sub03").hide();
        $(".sub04").hide();
        $(".sub05").hide();
    });
    $(".sub_menu").mouseleave(function(){
        $(".sub_menu").hide();
    });
    $(".logo").mouseover(function(){
        $(".sub_menu").hide();
    });
});